# -*- coding: utf-8 -*-
"""SimpleRISC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWXfVZGVoydkNumKiV1f9UhfrzCpm3ll

SimpleRISC Assembler
"""

isa_opcodes = {
    "ADD":  "00000", "SUB":  "00001", "MUL":  "00010", "DIV":  "00011",
    "MOD":  "00100", "CMP":  "00101", "AND":  "00110", "OR":   "00111",
    "NOT":  "01000", "MOV":  "01001", "LSL":  "01010", "LSR":  "01011",
    "ASR":  "01100", "NOP":  "01101", "LD":   "01110", "ST":   "01111",
    "BEQ":  "10000", "BGT":  "10001", "B":    "10010", "CALL": "10011",
    "RET":  "10100"
}

registers = {
    "R0":  "0000", "R1":  "0001", "R2":  "0010", "R3":  "0011",
    "R4":  "0100", "R5":  "0101", "R6":  "0110", "R7":  "0111",
    "R8":  "1000", "R9":  "1001", "R10": "1010", "R11": "1011",
    "R12": "1100", "R13": "1101", "R14": "1110", "R15": "1111"
}

def read_from_file(filename):
    lines = []
    with open(filename, 'r') as file:
        for line in file:
            no_comments = line.split('//')[0]
            clean_line = no_comments.strip().upper()
            if clean_line:
                lines.append(clean_line)
    return lines

def first_pass(lines):
    symbol_table = {}
    clean_instructions = []
    pc = 0
    for line in lines:
        if ':' in line:
            parts = line.split(':')
            label_name = parts[0].strip()
            symbol_table[label_name] = pc
            instruction = parts[1].strip()
        else:
            instruction = line.strip()

        if instruction:
            clean_instructions.append(instruction)
            pc += 4

    return symbol_table, clean_instructions

def parse_line(line):
    clean_line = line.replace(',', ' ').replace('[', ' ').replace(']', ' ')
    parts = clean_line.split()
    return parts

def dec_to_bin(num_str, bits):
    num = int(num_str)
    if num >= 0:
        return format(num, f'0{bits}b')
    else:
        return format((1 << bits) + num, f'0{bits}b')

#Instruction Encoding
def ass_0_type(parts):
    opcode = isa_opcodes[parts[0]]
    padding = "0" * 27
    return opcode + padding

def ass_1_type(parts, current_pc, symbol_table):
    if parts[1] in symbol_table:
        offset_int = int((symbol_table[parts[1]] - current_pc) / 4)
    else:
        offset_int = int(parts[1])
    offset_bin = dec_to_bin(str(offset_int), 27)
    opcode = isa_opcodes[parts[0]]
    return opcode + offset_bin

def ass_2_type_mov_not(parts):
    opcode = isa_opcodes[parts[0]]
    rd = registers[parts[1]]
    empty_rs1 = "0000"
    if parts[2] in registers:
        r_i = "0"
        rs2 = registers[parts[2]]
        padding = "0" * 14
        return opcode + r_i + rd + empty_rs1 + rs2 + padding
    else:
        r_i = "1"
        imm = dec_to_bin(parts[2], 18)
        return opcode + r_i + rd + empty_rs1 + imm

def ass_2_type_cmp(parts):
    opcode = isa_opcodes[parts[0]]
    rd = "0" * 4
    rs1 = registers[parts[1]]
    if parts[2] in registers:
        r_i = "0"
        rs2 = registers[parts[2]]
        padding = "0" * 14
        return opcode + r_i + rd + rs1 + rs2 + padding
    else:
        r_i = "1"
        imm = dec_to_bin(parts[2], 18)
        return opcode + r_i + rd + rs1 + imm

def ass_r_type(parts):
    opcode = isa_opcodes[parts[0]]
    r = "0"
    rd = registers[parts[1]]
    rs1 = registers[parts[2]]
    rs2 = registers[parts[3]]
    padding = "0" * 14
    return opcode + r + rd + rs1 + rs2 + padding

def ass_i_type(parts):
    opcode = isa_opcodes[parts[0]]
    i = "1"
    rd = registers[parts[1]]
    rs1 = registers[parts[2]]
    imm = dec_to_bin(parts[3], 18)
    return opcode + i + rd + rs1 + imm

def ass_mem_type(parts):
    opcode = isa_opcodes[parts[0]]
    r_i = "1"
    rd = registers[parts[1]]
    imm = dec_to_bin(parts[2], 18)
    rs1 = registers[parts[3]]
    return opcode + r_i + rd + rs1 + imm

#Selector
def assemble_instruction(parts, current_pc, symbol_table):
    if len(parts) == 1:
        return ass_0_type(parts)

    elif len(parts) == 2:
        return ass_1_type(parts, current_pc, symbol_table)

    elif len(parts) == 3:
        if parts[0] == "MOV" or parts[0] == "NOT":
            return ass_2_type_mov_not(parts)
        elif parts[0] == "CMP":
            return ass_2_type_cmp(parts)

    elif len(parts) == 4:
        if parts[0] in ["LD", "ST"]:
            return ass_mem_type(parts)
        elif parts[3] in registers:
            return ass_r_type(parts)
        else:
            return ass_i_type(parts)

#Main
def run_assembler(filename):
    # 1. Read and clean the file
    raw_lines = read_from_file(filename)

    # 2. First Pass
    symbol_table, clean_instructions = first_pass(raw_lines)

    # 3. Second Pass
    machine_code = []
    current_pc = 0
    for instruction in clean_instructions:
        parts = parse_line(instruction)
        binary32 = assemble_instruction(parts, current_pc, symbol_table)
        machine_code.append(binary32)
        current_pc += 4 # Move PC forward for the next instruction

    return machine_code
final_binary = run_assembler("SimpleRISC Test Program.asm")
for line in final_binary:
  print(line)